name: federated_learning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - amqp=5.2.0
  - backports.zoneinfo=0.2.1
  - billiard=4.2.1
  - blas=1.0
  - boto3=1.35.43
  - botocore=1.35.43
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - celery=5.4.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1
  - click-repl=0.3.0
  - colorama=0.4.6
  - contourpy=1.3.0
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - double-conversion=3.3.0
  - expat=2.6.3
  - filelock=3.16.1
  - flower=2.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.12.1
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - humanize=4.11.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jmespath=1.0.1
  - kiwisolver=1.4.7
  - kombu=5.4.1
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libclang13=19.1.2
  - libdeflate=1.22
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libpng=1.6.44
  - libsqlite=3.46.1
  - libtiff=4.7.0
  - libuv=1.49.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - markupsafe=3.0.1
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpmath=1.3.0
  - munkres=1.1.4
  - networkx=3.4.1
  - numpy=2.1.1
  - numpy-base=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - pcre2=10.44
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.43.4
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyparsing=3.2.0
  - pyside6=6.8.0
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch=2.5.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.0
  - requests=2.32.3
  - s3transfer=0.10.3
  - setuptools=70.3.0
  - six=1.16.0
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.13
  - torchaudio=2.5.0
  - torchvision=0.20.0
  - tornado=6.4.1
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vine=5.1.0
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
